export const SET_IMAGE_BY_TOPIC_IMAGE = 'SET_IMAGE_BY_TOPIC_IMAGE'
export const SET_IMAGE_BY_TOPIC_IMAGE_ERROR = 'SET_IMAGE_BY_TOPIC_IMAGE_ERROR'
export const SET_IMAGE_BY_TOPIC_IMAGE_CLERAR = 'SET_IMAGE_BY_TOPIC_IMAGE_CLERAR'
export const SET_IMAGE_BY_TOPIC_IMAGE_LOADING =
  'SET_IMAGE_BY_TOPIC_IMAGE_LOADING'
